name: pactive
description: Run Buddy pipelines from a client with webhook.
version: 1.0.0
homepage: https://github.com/viniciusantonioli/pactive

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^3.0.9
  jsonify: ^0.1.0
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
